# Generated by Django 5.0.1 on 2024-01-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='advertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Man',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('man_name', models.CharField(max_length=100)),
                ('man_description', models.TextField()),
                ('man_imaages', models.ImageField(blank=True, upload_to='home')),
            ],
        ),
        migrations.CreateModel(
            name='Woman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woman_name', models.CharField(max_length=100)),
                ('woman_description', models.TextField()),
                ('woman_images', models.ImageField(blank=True, upload_to='home')),
            ],
        ),
    ]
