# Generated by Django 5.0.1 on 2024-01-30 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yatishproduction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='man',
            old_name='man_imaages',
            new_name='man_images',
        ),
    ]
