# Generated by Django 5.0.1 on 2024-01-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatishproduction', '0002_rename_man_imaages_man_man_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='man',
            name='man_images',
            field=models.ImageField(blank=True, null=True, upload_to='home'),
        ),
        migrations.AlterField(
            model_name='woman',
            name='woman_images',
            field=models.ImageField(blank=True, null=True, upload_to='home'),
        ),
    ]
