# Generated by Django 4.2.4 on 2023-09-05 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firefitnesshub', '0002_trainer_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
