# Generated by Django 4.2.4 on 2023-09-06 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firefitnesshub', '0004_membership_delete_gymclass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
