# Generated by Django 4.2.5 on 2023-09-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firefitnesshub', '0006_remove_trainer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
