# Generated by Django 4.2.5 on 2023-09-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firefitnesshub', '0009_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, upload_to='about'),
        ),
    ]
